// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  swapfold() — reverses array in place
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: swapfold reverses even-length array", "[T1]")
{
    int numbers[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 0};
    int cnt = 10;
    swapfold(numbers, cnt);
    int expected[] = {0, 9, 8, 7, 6, 5, 4, 3, 2, 1};
    for (int i = 0; i < cnt; i++)
        REQUIRE(numbers[i] == expected[i]);
}

TEST_CASE("T1b: swapfold reverses odd-length array (middle stays put)", "[T1]")
{
    int numbers[] = {7, 8, 9, 4, 1};
    int cnt = 5;
    swapfold(numbers, cnt);
    int expected[] = {1, 4, 9, 8, 7};
    for (int i = 0; i < cnt; i++)
        REQUIRE(numbers[i] == expected[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  sumfold() — first-half[i] = number[i] + number[last-i-1]
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: sumfold of [1,2,3,4,5,6] gives first-half [7,7,7]", "[T2]")
{
    int numbers[] = {1, 2, 3, 4, 5, 6};
    int cnt = 6;
    sumfold(numbers, cnt);
    REQUIRE(numbers[0] == 7);  // 1 + 6
    REQUIRE(numbers[1] == 7);  // 2 + 5
    REQUIRE(numbers[2] == 7);  // 3 + 4
}

TEST_CASE("T2b: sumfold of odd-length [1,2,3,4,5] — first 3 = [6,6,6]", "[T2]")
{
    int numbers[] = {1, 2, 3, 4, 5};
    int cnt = 5;
    sumfold(numbers, cnt);
    REQUIRE(numbers[0] == 6);  // 1 + 5
    REQUIRE(numbers[1] == 6);  // 2 + 4
    REQUIRE(numbers[2] == 6);  // 3 + 3 (middle counted twice on odd)
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  equalfold() — equal[i] = 1 if number[i] == number[last-i-1] else 0
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: equalfold of palindrome [1,2,3,2,1] gives [1,1]", "[T3]")
{
    int numbers[] = {1, 2, 3, 2, 1};
    int equal[SIZE];
    int cnt = 5;
    equalfold(numbers, equal, cnt);
    REQUIRE(equal[0] == 1);  // 1 == 1
    REQUIRE(equal[1] == 1);  // 2 == 2
}

TEST_CASE("T3b: equalfold of mixed [3,5,7,5,2] gives [0,1]", "[T3]")
{
    int numbers[] = {3, 5, 7, 5, 2};
    int equal[SIZE];
    int cnt = 5;
    equalfold(numbers, equal, cnt);
    REQUIRE(equal[0] == 0);  // 3 != 2
    REQUIRE(equal[1] == 1);  // 5 == 5
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Integration — makearray + fold operations preserve invariants
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: swapfold applied twice restores original array", "[T4]")
{
    int numbers[SIZE], original[SIZE];
    int cnt = makearray(numbers);
    for (int i = 0; i < cnt; i++) original[i] = numbers[i];
    swapfold(numbers, cnt);
    swapfold(numbers, cnt);
    for (int i = 0; i < cnt; i++)
        REQUIRE(numbers[i] == original[i]);
}

TEST_CASE("T4b: sumfold output equals original[i] + original[cnt-i-1] for first half", "[T4]")
{
    int numbers[SIZE], original[SIZE];
    int cnt = makearray(numbers);
    for (int i = 0; i < cnt; i++) original[i] = numbers[i];
    sumfold(numbers, cnt);
    int half = static_cast<int>(ceil(cnt / 2.0));
    for (int i = 0; i < half; i++)
        REQUIRE(numbers[i] == original[i] + original[cnt - i - 1]);
}
